# Generated by Django 5.2.3 on 2025-07-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='student_id',
            field=models.TextField(null=True),
        ),
    ]
